### ISSUE TITLE
Nice plugin

### ISSUE THREAD

**Issue by netun0** [vitorhirota/plugin.video.globotv#6]
here I see the programs list but when I click it show "addon.py error"

Thanks

**Comment by vitorhirota** [comment]
@netun0, you are saying you can't go past the shows into the videos list?

**Comment by max-vmcode** [comment]
Hi Vitor!
I'm using your plugin and I'm getting too this error trying to opening any video.

As my wife is brazilian we have a payed account in which we can access "para assinantes" section but on any of these we are receiving this error..
Can you try to see if it's working? Maybe Globo changed something in videos and you need to update your plugin!
BTW, many thanks for your hard work! It's very useful!

Muito obrigado mesmo!
Max

**Comment by vitorhirota** [comment]
@p2pow350, yeah, I'm aware of this problem, but am kind of out of time right now to look into it...

I will try to get this done through the weekend and suggest you follow up the thread on xbmc's forum.
http://forum.xbmc.org/showthread.php?tid=145951&pid=1477091#pid1477091

I will post up there once I get this done.

Cheers

**Comment by max-vmcode** [comment]
Many thanks for your fast answer! Yes, I'm already following this thread and as everyone's report was that the plugin is not working I asked myself, why don't you ask directly to the master?
BTW, thank you so much!
Cheers
Max

**Comment by max-vmcode** [comment]
Hi Vitor,
is there something I can do for let this plugin work?
I'm a programmer, maybe I can help you to fix this plugin..
The issue, is something related to the PATH of the videos or it's something else?

Thank you so much
Cheers
Max

**Comment by vitorhirota** [comment]
The actual issue is that the hash globo.tv server require to start streaming has changed.

[resources/lib/util.py](https://github.com/vitorhirota/plugin.video.globotv/blob/master/resources/lib/util.py) has a class `hashJS`, which is a translation from js to python of http://s.videos.globo.com/p2/j/api.min.js

Globo has changed this javascript api, so, in order for the plugin to work again, one have to "retranslate" it again.

If you are familiar with javascript, you are totally welcome to patch the python file up, and you can then just open up a pull request here.

Coincidentally, I've just sit up to finally take a look at this (while watching Monza Grand Prix =P), but you are totally welcome to help up if you can!

**Comment by vitorhirota** [comment]
fixed in 1cc60ab24874b2c2dfe8c823d463af46ff088837
