### ISSUE TITLE
Only HD quality available

### ISSUE THREAD

**Issue by max-vmcode** [vitorhirota/plugin.video.globotv#9]
Hi Vitor,
this is not really an issue but even if quality is set to "SD Only" all videos I'm trying to see are in HD.
This is not really an issue but since DSL are not usually so fast I got any video buffering all times..
I'm making some tests with different videos, novelas, variedades, etc..

BTW, I can't stop making greetings to you for your incredible work and for the effort you are dedicating to keep your plugin always updated...the challenge to convert globo API to python is very hard!

Muito obrigado
Deus abençoe voce!

**Comment by vitorhirota** [comment]
Hi@p2pow350, glad it has been useful :)

I've just tested myself, and had not any problems. 

Do you see this behavior for a specific video?

This seems counter intuitive, but in my tests. Videos in SD would buffer much more often than HD. Videos in SD actually, wouldn't start before full buffering, which did not happen for HD videos.

Out of my head, this could be related to a xbmc setting, instead.

I'm closing this issue here, and in the future, please feel free to open a new one, but in bitbucket (link is up on the readme), new home of the plugin.

Cheers.

**Comment by vitorhirota** [comment]
Well, actually, disregard what I've said. This could be related to globo's capabilities as well...

Anyhow, could not find any issues with the HD/SD option.

If you have any other evidence, please send it over and I will gladly take a look.
